### PR TITLE
Add fr_FR folder

### PR DESCRIPTION
**Pull request by LeDeutsch**
Every plugins and the cfg/std/ui .mo files

So as promised days ago. 
This is my pull request.
If there is any issues let me know and i'll correct it.

Have a great one!

### CODE REVIEW

**Comment by GPBeta** [comment]
Hi, I found that there're only translation binary files in this commit, 
so you didn't translate SAO Utils from the source files (*.po)?

**Comment by LeDeutsch** [comment]
I did. If you need the (.po) files i can send them aswell. I did just sent the (.mo) for now De : Joshua GPBetaEnvoyé le :jeudi 18 novembre 2021 14:11À : NERvGear/localesCc : Dinspel Ludwig Junior; AuthorObjet :Re: [NERvGear/locales] Add fr_FR folder (PR #8) Hi, I found that there're only translation binary files in this commit,so you didn't translate SAO Utils from the source files (*.po)?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LeDeutsch** [comment]
I did. 
If you need the (*.po) files i can send them aswell. I did just sent the (*.mo) for now

**Comment by GPBeta** [comment]
OK, there's no need to ".mo files, so committing the *.po files is enough.

**Comment by LeDeutsch** [comment]
> 
> 
> OK, there's no need to ".mo files, so committing the *.po files is enough.

Oh well, my bad. I've finally added all of the files including the .mo aha. I'll delet them and let the .po only. :)
And thank you for your time!

EDIT : there's only the .po files right now :)

**Comment by GPBeta** [comment]
Hi, I have created a new commit basing on this pull request: 54261c9e2a052828cab99e615ded47788e1ee1d4.
Please remember to run `git pull --rebase` first If you want to update your translation.

Now you can select "French" language in Steam, please try it out in `beta` branch.

Again, thank you very much for your contribution to SAO Utils!

**Comment by LeDeutsch** [comment]
Hello there, 
Sorry for the late I wasn't able to use my computer.

Everything is ok, also there's the language "Français" too.
But I'm into a problem, actually even with the Fr lang checked over steam SAO Utils still launching in En lang.

Maybe it's isn't a problem i really dunno how Steam games are working with aha.
Well, especially thanks to you to have created SAO Utils, I'm very happy to use it everyday

**Comment by GPBeta** [comment]
Did you switch to the `beta` branch in Steam's property page for SAO Utils?

**Comment by LeDeutsch** [comment]
Oh okay.
Well so everything is ok.
I did not see any kind of bug or mistake.

Thank you again, I'll keep my translation up to date for the futurs updates :)

**Comment by GPBeta** [comment]
That's great! I'll apply the changes to the default branch.

**Pull request closed without merging**
