### PR TITLE
Update tr translation

### PR DESCRIPTION
**Pull request by Lawliet0**

### CODE REVIEW

**Comment by Lawliet0** [comment]
I really liked the latest version of sao utils.
Are you considering adding more features?

**Comment by Lawliet0** [comment]
did i do wrong?

**Comment by GPBeta** [comment]
> I really liked the latest version of sao utils. Are you considering adding more features?

Yeah, that's great. I'm working on Free Customizing mode for the HUD Widget and a new RSS Feed Widget currently.

> did i do wrong?

It looks good to me now :)

**Comment by Lawliet0** [comment]
> > Sao utils'in en son sürümünü gerçekten beğendim. Daha fazla özellik eklemeyi düşünüyor musunuz?
> 
> Evet bu harika. HUD Widget'ı için Ücretsiz Özelleştirme modu ve şu anda yeni bir RSS Feed Widget'ı üzerinde çalışıyorum.
> 
> > yanlış mı yaptım
> 
> Şimdi bana iyi geliyor :)

This is great.
I requested the RSS Feed Widget.
I'm so glad it was taken care of so quickly.
Thank you for your hard work on this project.
Thanks to you, I got the application I wanted.

**Comment by Lawliet0** [comment]
i needed to update some parts so i updated two files

**Comment by GPBeta** [comment]
Looks good to me, thanks for the translations!

**Pull request merged**
